### ISSUE TITLE
Request: Constantly stealing focus.

### ISSUE THREAD

**Issue by Omniphantasm** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#10]
Any way you could implement something that prevents it from spamming windows that steal focus everytime it does something?

Ideally headless mode would be the solution to that but headless doesn't seem to work at all for me and I'm not sure why.

Also any way to make it minimize to system tray instead of task bar? Not a big deal just a minor personal preference on that one 😁

**Comment by farshadz1997** [comment]
Sorry, there isn't any way to make this work.
running in headless mode can cause so many bugs and it's difficult to debug them.

**Comment by Omniphantasm** [comment]
Ah well, still better than doing it manually. 

I'll just schedule it for when I'm asleep 🤣 

Thanks!
