### ISSUE TITLE
[Bug & Feature request] Add a second E-Mail for security pop up

### ISSUE THREAD

**Issue by timfischbach** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#100]
[BUG]

On fresh accounts, the security pop up: "Add a second E-Mail for safety" sometimes appeares, which lefts the script confused, thus can't continue.

Picture of the pop up:
![Screenshot_7](https://github.com/farshadz1997/Microsoft-Rewards-bot-GUI-V2/assets/59933715/acc7a0fc-8f82-4a3b-abc1-c1e35fab774e)

A quick fix for the script would be to press the small blue text, if the popup appears. :) That way, you'll never deal with it again the next 7 days.
_______________________________________________________________________________
[FEATURE]

But what about after 7 days? Fake Mails aren't an option, because the second E-Mail is probably used to send you a code to login. Maybe using other Microsoft accounts to link them to each other, so that the script can finish the verification alone?

MS Account 1 ----------verification email---------> MS Account 2 (opened in a separate tab (Incognito or other profile?))
And to make it simple, we link the 2nd acc to the first one
MS Acc 2 -----------verification mail-----> MS Acc 1

That way, we can't loose the E-Mail access and have a automated process :))))))))

But it's just a thought. Maybe there is a more simple way to this issue?
Anyway thank's for your nice project :D

**Comment by farshadz1997** [comment]
Hi,

I can add a method to click on skip but creating a function for this requires API or scraping E-mail providers (Gmail, Outlook, Yahoo, etc) which is not possible.

**Comment by timfischbach** [comment]
That would be nice. Btw this popup is showing everyday, so it's sadly not a one time reminder :)

**Comment by farshadz1997** [comment]
even with that skip you have to add backup email after that, you don't have any other choice then

**Comment by timfischbach** [comment]
Small Update: Apparently you can use a single backup E-Mail for multiple MS accounts.

**Comment by timfischbach** [comment]
Fix for this is just adding the E-Mail address. It's not used as 2FA, so it's just about entering one. But idk if you need it for redeeming, so DON'T use a throw away mail. Just use a fresh E-Mail for only those mails :)
