### ISSUE TITLE
Unable to start the program

### ISSUE THREAD

**Issue by RealPogger** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#104]
When I start the program it says: "There was an error while processing your request: [Errno 13] Permission denied: 'C:\\Users\\JUSTIN~1\\AppData\Local\Temp\\Temp\\_MEI184042". I tried redownloading the program and deleting the temp folders but the error still persist when I try to fix it. When I delete all of the temp files it just makes a new one and says it doesn't have permission. Here is my errors.txt file to give a log of what happened: [errors.txt](https://github.com/farshadz1997/Microsoft-Rewards-bot-GUI-V2/files/11522105/errors.txt)

**Comment by W-D-D** [comment]
Same for me Justin

**Comment by RealPogger** [comment]
I fixed the issue by deleting the folder in AppData
