### ISSUE TITLE
default profile is automatically signed-in, while using session mode.

### ISSUE THREAD

**Issue by NakulPrasad** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#106]
in ms-edge, suppose i used my private microsoft account with name : ABC. Now, when i add new account in accounts.json, and session is on, then new session automatically has ABC signed in. 
I have to stop program and manually remove profile, then restart. (in both PC and Mobile)
Please do something as it becomes frustrating with 10+ accounts.

**Comment by farshadz1997** [comment]
please check this out https://github.com/farshadz1997/Microsoft-Rewards-bot/issues/331

**Comment by NakulPrasad** [comment]
Issue resolved
