### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Hxsh1337** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#116]
![image](https://github.com/farshadz1997/Microsoft-Rewards-bot-GUI-V2/assets/131890306/f7ebc299-0468-47fc-8b1e-47e32d9ac073)

**Comment by blover2009** [comment]
me too!

**Comment by RealPogger** [comment]
I fixed this issue by going to C:\Users\Your Username Here\AppData\Roaming\Microsoft Rewards Farmer and deleting shared_preferences.json.

**Comment by RealPogger** [comment]
You will lose all of your settings but it seemed to fix the problem for me
