### ISSUE TITLE
After the new Microsoft patches, MSN shopping no longer works.

### ISSUE THREAD

**Issue by Chappie18** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#117]
As terminal one is updated to the latest features, the GUI falls behind, and MSN shopping does not work, where it does in terminal one.

**Comment by farshadz1997** [comment]
both has same code for MSN shopping game

**Comment by Vipin2003** [comment]
MSN shopping works...but the issue is that we have to run the bot again after ressetting log. It misses the game on some account.

**Comment by Chappie18** [comment]
> MSN shopping works...but the issue is that we have to run the bot again after ressetting log. It misses the game on some account.

Yeah, that's the issue; I just reported it as a whole.

**Comment by Vipin2003** [comment]
It's working, just reset logs of all of ur accounts and restart the bot. I think that it's a bug ehich @farshadz1997 needs to be fixed. Bot v1 is working fine.
