### ISSUE TITLE
Mobile search error

### ISSUE THREAD

**Issue by itsHenry35** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#13]
![image](https://user-images.githubusercontent.com/58730749/221202603-3302e485-6a35-48df-a300-88d9e2b09962.png)

**Comment by farshadz1997** [comment]
This is not come from farmer, it's not important, what is your problem with mobile search?

**Comment by itsHenry35** [comment]
> This is not come from farmer, it's not important, what is your problem with mobile search?

browser closes instantly after logging in for mobile search, desktop search is all right, mobile search was all right, but this has happened since last night

**Comment by farshadz1997** [comment]
it just didn't start searching after logging in, am I right?

**Comment by itsHenry35** [comment]
> it just didn't start searching after logging in, am I right?

yes

**Comment by farshadz1997** [comment]
Maybe it just couldn't get the words to search them, I'll fix the backup method.
