### ISSUE TITLE
Failed to read XDG desktop portal settings

### ISSUE THREAD

**Issue by JittoJoseph** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#19]
Getting this error when i try to run 'python3 main.pyw'

** (flet:28502): CRITICAL **: 18:02:42.072: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (flet:28502): CRITICAL **: 18:02:42.075: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
![Screenshot from 2023-03-03 18-02-46](https://user-images.githubusercontent.com/78639807/222722322-f08c5ff1-53cf-4641-a446-6055109719d3.png)

**Comment by JittoJoseph** [comment]
I am running Ubuntu 20 with gnome desktop

**Comment by farshadz1997** [comment]
Hello,
Look for it in Flet issues. https://github.com/flet-dev/flet
