### ISSUE TITLE
Slower searches

### ISSUE THREAD

**Issue by gempath** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#2]
Is it possible to slow the searches down just a bit?

**Comment by farshadz1997** [comment]
Could you please say your reason? because most people say it is too slow with this speed.

**Comment by gempath** [comment]
I'm not sure a person running their account would search quite that fast.  Maybe an option to slow the bot by half on the searches?

**Comment by farshadz1997** [comment]
I'm not sure to add it, but I can give you modified script to search it slower, just replace old ```farmer.py``` in ```src>core``` with this new one.
[farmer.zip](https://github.com/farshadz1997/Microsoft-Rewards-bot-GUI-V2/files/10760849/farmer.zip)

**Comment by gempath** [comment]
Great, thanks.
