### ISSUE TITLE
No errors, does nothing

### ISSUE THREAD

**Issue by Harktavius** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#20]
I'm not experienced with this, but I've put the webdrivers into the windows folder on my C drive and pip installed all the dependencies in the requirements.txt. I put my account information in, but when I tell it to start, nothing happens. No errors.  Not sure what I'm doing wrong.

**Comment by JittoJoseph** [comment]
same thing for me

**Comment by Harktavius** [comment]
So I was able to get it to work by putting the web drivers into the parent directory of the script, not in a subfolder. Just the exe files.

**Comment by farshadz1997** [comment]
> I'm not experienced with this, but I've put the webdrivers into the windows folder on my C drive and pip installed all the dependencies in the requirements.txt. I put my account information in, but when I tell it to start, nothing happens. No errors. Not sure what I'm doing wrong.

@Harktavius  @JittoJoseph This happens when bot can't find the Web driver.

**Comment by JittoJoseph** [comment]
Thanks, it works!
