### ISSUE TITLE
Number of accounts used by a single IP

### ISSUE THREAD

**Issue by OwnerCM** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#22]
How many accounts can be used for a single IP？

**Comment by farshadz1997** [comment]
Microsoft says in TOS up to 6 account per household.

**Comment by OwnerCM** [comment]
> Microsoft says in TOS up to 6 account per household.

Thank you. By the way, could you add an execution log? I found that my account always failed to perform mobile search, but it was successfully completed

**Comment by farshadz1997** [comment]
what's the error, turn on save errors and send it for me
