### ISSUE TITLE
"msedgedriver" needs to be in PATH

### ISSUE THREAD

**Issue by ZetingZ** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#24]
it does not state where to put the edge driver, i tried to extract the edge driver folder into C:\Windows but it won't work

**Comment by ZetingZ** [comment]
If it was my problem then can you please add a detailed tutorial in the readme because that would be really helpful, thank you!

**Comment by farshadz1997** [comment]
You need to put msedgedriver.exe in C:/windows or bot directory, don't put msedgederiver in any folder
