### ISSUE TITLE
error writing to errors.txt on startup

### ISSUE THREAD

**Issue by W5x** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#3]
hello, the following error is writing in errors.txt on every startup of the app

> 
> -------------------2023-02-16 17:17:46.189195-------------------
> 
> APP_ERROR:
> type 'bool' is not a subtype of type 'List<dynamic>?' in type cast
> 
> -------------------2023-02-16 17:18:04.068512-------------------
> 
> APP_ERROR:
> type 'bool' is not a subtype of type 'List<dynamic>?' in type cast
> 
> -------------------2023-02-16 19:39:51.022994-------------------
> 
> APP_ERROR:
> type 'bool' is not a subtype of type 'List<dynamic>?' in type cast
> 
> -------------------2023-02-16 21:50:33.193439-------------------
> 
> APP_ERROR:
> type 'bool' is not a subtype of type 'List<dynamic>?' in type cast

nice UI by the way , good work m8 , keep it up.

**Comment by farshadz1997** [comment]
Hello,
this error is not important; however, I couldn't find the reason for this error, but it wouldn't make problem for bot.
