### ISSUE TITLE
Reset logs for all accounts button

### ISSUE THREAD

**Issue by 80sVectorz** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#30]
Just a button to quickly reset logs for all accounts.

**Comment by W5x** [comment]
i was going to ask about it , also if you can add checkbox beside every account to select which accounts you need to reset.

**Comment by leatherhead645** [comment]
Hi @80sVectorz @W5x, 
You can check out my Modified Folder that is still work in progress for other features that I haven't got to work on cause laziness. 
https://github.com/leatherhead645/Microsoft-Rewards-bot-GUI-V2
