### ISSUE TITLE
2FA/Session Login Issue

### ISSUE THREAD

**Issue by gangstashiba** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#33]
Using 2FA with session enabled works fine when doing the web browser portion of the searches as you can open the session from the program and login manually, You can't do this with the mobile agent.

Is it possible for you to allow us to open a session with the mobile agent or have the bot pause when this happens instead of immediate termination? Thanks.

**Comment by farshadz1997** [comment]
it won't be implemented, for using bot you should not use your main account and burner accounts don't have 2FA.
