### ISSUE TITLE
Farm, open a free VPN, farm again and close VPN

### ISSUE THREAD

**Issue by riahc3** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#34]
Hello

From what it seems, it possible to farm from two different locations per day to double the farming.

It would be nice to integrate this automatically some way. ProtonVPN comes to mind as being free.

Thank you

**Comment by farshadz1997** [comment]
Hi, 

sorry for long delay, I forgot to reply to you. Actually this not possible because not everyone use Proton VPN and it would be useless to add this.
