### ISSUE TITLE
error - bool

### ISSUE THREAD

**Issue by LPridemore** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#4]
I get this a lot:

APP_ERROR:
type 'bool' is not a subtype of type 'List<dynamic>?' in type cast 
*Never mind. I see you have already dealt with this error on the Closed tab.
BUT can this help you: 
https://stackoverflow.com/questions/72239841/type-bool-is-not-a-subtype-of-type-liststring-in-type-cast-flutter-dart

I also see it not doing the Warpspeed Quiz. Is that coming soon?

**Comment by farshadz1997** [comment]
Warpspeed quiz? Where is that?
This error comes from framework I guess which converts python code to flutter, I don't think I can fix that

**Comment by LPridemore** [comment]
Here's a screenshot of the Warpspeed Quiz tile on Dashboard.

**Comment by farshadz1997** [comment]
@LPridemore, I think you forgot to attach screenshot.

**Comment by LPridemore** [comment]
Sorry. I attached it in the email reply. I guess it doesn't post it here along with email reply comment. 
[https://i.imgur.com/2igGSaL.jpg](url) there it is.
