### ISSUE TITLE
Main.pyw runs but doesnt work

### ISSUE THREAD

**Issue by zumokuta** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#42]
No matter what I do, it doesnt work. I factory restarted my  laptop currenty and it stopped working once i downloaded the new code. It doesnt give status, points, error nothing.

**Comment by farshadz1997** [comment]
try run this rest setting with this app [reset_settings](https://github.com/farshadz1997/Microsoft-Rewards-bot-GUI-V2/files/11048585/reset_settings.zip) and then open app again.
does this one still work on yours https://github.com/farshadz1997/Microsoft-Rewards-bot-GUI-V2/releases/tag/1.0 ?

**Comment by zumokuta** [comment]
I did that and even installed it again but it still doesnt work for some reason it just starts but doesnt change the section current points detail or proxy, it just shows the account email
