### ISSUE TITLE
Anyone else have problems with it failing to complete 1 out of 3 almost every day?

### ISSUE THREAD

**Issue by Omniphantasm** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#45]
Seems like every morning when I wake up I have to click over and do the quiz myself without fail. 

Keep dropping my streak because I forget 😭

**Comment by farshadz1997** [comment]
which quiz?

**Comment by Omniphantasm** [comment]
Was 

Know your celebrity news?
Test your pop culture IQ with our weekly entertainment quiz

This time, but it's almost always consistently the quiz that fails to finish for me regardless of type.
