### ISSUE TITLE
There was an error while processing your request: time data 'Unknown error'

### ISSUE THREAD

**Issue by darkyng** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#46]
Thank you for your work, 
this issue started from today
the date and time are correct,
![image](https://user-images.githubusercontent.com/86430514/228529216-5295e6dc-1bd9-45c0-a6ba-9c988780b4cd.png)

**Comment by darkyng** [comment]
redownloaded , now the error is this, i've configured the .json but i cant select it because it locks on this autostart ![image](https://user-images.githubusercontent.com/86430514/228537155-085a8e1f-2d4d-4116-84fe-5c3af2ebb704.png)

**Comment by darkyng** [comment]
Unfortunately no errors.txt or log, the reset settings worked like a charm though, thank you very much!

**Comment by farshadz1997** [comment]
fixed the issue in 88dc514
