### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Ciao223344** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#50]
I receive this after I press the start button :

`
-------------------2023-04-05 13:18:26.034693-------------------
Message: unknown error: Could not remove old devtools port file. Perhaps the given user-data-dir at C:\Users\leona\Desktop\Microsoft-Rewards-bot-GUI-V2-1.2/Profiles/iosonorocco@outlook.it
/PC is still attached to a running Chrome or Chromium process
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010BDCE3+50899]
	(No symbol) [0x0104E111]
	(No symbol) [0x00F55588]
	(No symbol) [0x00F74E53]
	(No symbol) [0x00F70DC7]
	(No symbol) [0x00F6F479]
	(No symbol) [0x00FA1FFE]
	(No symbol) [0x00FA1CEC]
	(No symbol) [0x00F9B6F6]
	(No symbol) [0x00F77708]
	(No symbol) [0x00F7886D]
	GetHandleVerifier [0x01323EAE+2566302]
	GetHandleVerifier [0x013592B1+2784417]
	GetHandleVerifier [0x0135327C+2759788]
	GetHandleVerifier [0x01155740+672048]
	(No symbol) [0x01058872]
	(No symbol) [0x010541C8]
	(No symbol) [0x010542AB]
	(No symbol) [0x010471B7]
	BaseThreadInitThunk [0x76657D49+25]
	RtlInitializeExceptionChain [0x77CFB74B+107]
	RtlClearBits [0x77CFB6CF+191]
`

**Comment by Ciao223344** [comment]
How can i resolve it?

**Comment by farshadz1997** [comment]
It looks like your session trying to connect attached to another process. try run it with session off.

**Comment by Ciao223344** [comment]
I didn't understand, sorry

**Comment by Ciao223344** [comment]
Ok, i'll try, thanks

**Comment by Ciao223344** [comment]
It works, thanks a lot
