### ISSUE TITLE
how to add other accounts

### ISSUE THREAD

**Issue by tomo-Mik** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#51]
i used to use the old bot before this one, and idk how to properly add extra accounts in the json file. this is the way some tutorial taught me on the old bot but it didnt even work then. this is my layout someone help pls.

[
    {
        "username": "***********************",
        "password": "*************"

        "username": "***********************",
        "password": "*************"
    
        "username": "************************",
        "password": "*************"
    }
]

**Comment by farshadz1997** [comment]
each account credentials must be in a bracket like this:

```accounts.json
[
    {
        "username": "***********************",
        "password": "*************"
    },
    {
        "username": "***********************",
        "password": "*************"
    },
    {
        "username": "************************",
        "password": "*************"
    }
]

```
for your last account you must not put comma after close bracket. In this version you could add your account easily through GUI in Accounts page.

**Comment by tomo-Mik** [comment]
ok ty
