### ISSUE TITLE
Chrome Web Driver outdated error

### ISSUE THREAD

**Issue by shimi269** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#58]
I keep getting Chrome Web Driver outdated errors when trying to use it. I have try many different versions of the web driver, for the beta release and stable, and also placed it inside of the X:/Windows and Farmer folders. Chrome does load up for less than a second before closing again and giving this error;.

-------------------2023-04-15 09:02:44.594778-------------------
APP_ERROR:
Converter Function Error: Null check operator used on a null value

**Comment by farshadz1997** [comment]
Just get the one that is same as your browser. I think it's 112

**Comment by shimi269** [comment]
That's what i used, and it still gives the same error

**Comment by shimi269** [comment]
I have used a fresh install of Chrome 112.0.5615 and the same ChromeDriver, and I still get the same error

**Comment by shimi269** [comment]
Update: If anyone has this error. I turned on Sessions, then ran, and went to /path/Profiles\*yourmsemail*\PC\ and opened up the Last Version file. Mine read as '98.0.4758'. So i downloaded the respective ChromeDriver and it worked. I'm not sure why it isn't using the latest version of Chrome that I have installed on the machine, but for now it is working.

**Comment by farshadz1997** [comment]
Interesting, mine is 112.

**Comment by shimi269** [comment]
Found the issue in the end, their was an old version of Chrome hidden away in Program(x86) folder which is kept referring too. Once it was deleted the newer version of Chrome is now launched instead and everything works great.
