### ISSUE TITLE
Webdriver Error

### ISSUE THREAD

**Issue by YourAverageModder** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#64]
Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by darkyng** [comment]
Similar Issue with msedgedriver.exe 
![image](https://user-images.githubusercontent.com/86430514/233130368-a69d990e-29ec-416e-b8c1-2499733bed82.png)

![image](https://user-images.githubusercontent.com/86430514/233131185-e32a5c1f-a512-4ccf-8332-6fb6ee83af7f.png)


Troubleshoot:
- downloaded last version bot 1.4 
- downloaded last version msedgedriver 
![image](https://user-images.githubusercontent.com/86430514/233130566-dc73925d-7721-4df5-887a-5302d9028767.png)

- in pc user agent it sees an old version 
![image](https://user-images.githubusercontent.com/86430514/233131022-78b69096-7c76-4eed-aac5-5a97eb5faa03.png)
![image](https://user-images.githubusercontent.com/86430514/233131285-7535c004-96f8-4f6e-81a9-4210c1a3f84b.png)

thank you for your hard work

**Comment by farshadz1997** [comment]
This is not bot issue, you need save webdriver in bot path or c:/windows.

Your edge webdriver needs to be same as your browser, i'm almost sure you're not using canary version
