### ISSUE TITLE
[Errno 21] Is a directoy

### ISSUE THREAD

**Issue by Stinker666** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#68]
When I try to run the main.pyw on Ubuntu 22.04 I get this Error.
I'm running a terminal from the Farmer directory and use "python3 main.pyw" to run it.

**Comment by Balaji-Kotni** [comment]
@Stinker666, @farshadz1997  I have created a patch and raised a PR.

**Comment by farshadz1997** [comment]
Thanks, fixed in #69
