### ISSUE TITLE
Permission denied on startup

### ISSUE THREAD

**Issue by mrchief** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#70]
![image](https://user-images.githubusercontent.com/781818/233804076-4c98ed83-9bbc-4cea-8c2a-26fa48610c99.png)

I tried running it as an admi but it still gives the same error. I cleaned out temp files too but it tries to create this folder and fails.

**Comment by farshadz1997** [comment]
Have you tried source code as well and run it with Python? I'm aware of this, it comes from windows and I still couldn't find a proper way to fix it.

**Comment by CN-Patrick** [comment]
i have the same error

**Comment by farshadz1997** [comment]
get the latest commit and use it

**Comment by mrchief** [comment]
Running `main.pyw` worked as in it came up with the GUI. I downloaded the matching edge webdriver but then it gets into the login loop mentioned in #61. It also closes and reopens edge everytime.

**Comment by mrchief** [comment]
Ok, turning on `Seesion` flag seemed to fix it.

**Comment by farshadz1997** [comment]
> Running `main.pyw` worked as in it came up with the GUI. I downloaded the matching edge webdriver but then it gets into the login loop mentioned in #61. It also closes and reopens edge everytime.

Try use chromedriver instead, using edge can led to error.
