### ISSUE TITLE
Errno 13

### ISSUE THREAD

**Issue by actualpaca** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#71]
On startup, this message appears:

![errno13](https://user-images.githubusercontent.com/47336286/233805742-a400b1b6-180e-44f1-8998-7c8c3ee4dff5.PNG)

There was an error while processing your request: [Errno 13] Permission denied: 'C:\Users\CURRENT USER\AppData\Local\Temp\_MEI153242'

The program will subsequently need to be closed, and the file folder specified in the error will vanish, only to reappear when the program is opened again and the error reoccurs.
Before this behavior, the program and all associated files were moved to a different folder than the one they were originally run from and I switched from the Chrome web driver to the Edge web driver. Initially, it worked, but when I selected new colors for the GUI one toggle button did not change. I exited out and on the next restart, the error began. Running as administrator resulted in the same error. Tried deleting the accounts.json file and web drivers to see if that would help, but it did not. Restarted the computer, and the error persisted after.
I'm running Windows 10 64bit, with all current updates (4/22/2023) applied.

(Also, I realize that someone else also had this error and posted about it around an hour prior to this ticket, but I felt that it might be prudent to throw my experience and subsequent troubleshooting into the mix.)

**Comment by farshadz1997** [comment]
Have you tried source code as well and run it with Python? I'm aware of this, it comes from Windows and I still couldn't find a proper way to fix it.

**Comment by ZEERDEER** [comment]
I also have this error.
![image](https://user-images.githubusercontent.com/10573857/235334229-be95137f-19a6-4e7f-9879-d3070da9c987.png)

**Comment by farshadz1997** [comment]
try to use the latest source code for now.

**Comment by ziadOUA** [comment]
Any update ? I'm encountering this problem too. Thanks.

**Comment by farshadz1997** [comment]
@ziadOUA  have you tried the newest commit?

**Comment by ziadOUA** [comment]
Yes. I first encountered this issue when using the executable. I then tried to use the program directly from the source code : I download the requirements, but then, when I executed main.pyw, I just encountered the same error. 
But when I executed it from PyCharm : no issues (?)

Thanks @farshadz1997

**Comment by farshadz1997** [comment]
> Yes. I first encountered this issue when using the executable. I then tried to use the program directly from the source code : I download the requirements, but then, when I executed main.pyw, I just encountered the same error. But when I executed it from PyCharm : no issues (?)
> 
> Thanks @farshadz1997

try this one https://github.com/farshadz1997/Microsoft-Rewards-bot-GUI-V2/archive/refs/heads/master.zip

**Comment by ziadOUA** [comment]
Same problem @farshadz1997

**Comment by timfischbach** [comment]
Downloading the master branch and executing it fixed it for me.
