### ISSUE TITLE
Why so much delay ?

### ISSUE THREAD

**Issue by akgupta0777** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#72]
I looked through your source code and found out delays to be too long.
You used a uniform random function to generate a delay from a range 
The range comes to be [3,9] seconds on doing bing searches. Can't we minimize it so that it will take less time to farm accounts ?.

What are the challenges coming the way to implement or reduce shorter delays ?

**Comment by farshadz1997** [comment]
delays must be in bot, otherwise, your account may get banned, it should act humanize.

**Comment by akgupta0777** [comment]
> delays must be in bot, otherwise, your account may get banned, it should act humanize.

I can agree with you but if you look at the ABS extension that do searches with a delay of 1.6 seconds doesn't got any of my accounts ban.

As far as getting a ban your bot or any bot can also result in a ban.

**Comment by farshadz1997** [comment]
You can change it for yourself and redcue delays
