### ISSUE TITLE
Erno 22

### ISSUE THREAD

**Issue by dtigress** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#74]
![image](https://user-images.githubusercontent.com/131223131/234027066-64a1926a-d9b3-433e-a0ee-0705d85a67a5.png)

I was also getting Erno 13.

**Comment by farshadz1997** [comment]
Hi, can you please extract and replace this in ```bot_directory/src/core``` and tell me result?
[other_functions.zip](https://github.com/farshadz1997/Microsoft-Rewards-bot-GUI-V2/files/11311472/other_functions.zip)

**Comment by sadhritesh** [comment]
I replaced it but still not working .

**Comment by farshadz1997** [comment]
still the same error?

**Comment by sakuiamgay** [comment]
Any fix for this yet?

**Comment by dtigress** [comment]
Still not working with the file swap. I'll try the last version.

**Comment by dtigress** [comment]
Previous version is Erno 13: Permission Denied
