### ISSUE TITLE
Parallel Bot Support

### ISSUE THREAD

**Issue by akgupta0777** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#82]
I want to run these bots in parallel to each other like running both instance of flet app. But having issue doing so. Dont know why
As soon you open the flet app the apps are connected to each other like if i change something in one instance of app it will reflect in other instance too.

Can we have support for parallel bots working in same device

**Comment by farshadz1997** [comment]
yes, you can't use multiple instances of this. I'm not planning to add the parallel feature for this right now or at least I won't publish it here in GitHub

**Comment by akgupta0777** [comment]
But isn't there any way to use multiple instances. Why you are not planning to add this ? Do you want help I can help

**Comment by farshadz1997** [comment]
The common feature among all bots that have been removed by Microsoft was the parallel feature. that's why I don't want to add it.
