### ISSUE TITLE
Could not remove old devtools port file

### ISSUE THREAD

**Issue by LinhLe128** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#94]
How can i fix this problem ? When i click start and nothing happen 

![Screenshot 2023-05-14 111225](https://github.com/farshadz1997/Microsoft-Rewards-bot-GUI-V2/assets/90230859/7c8dc104-164b-4c5f-8ec1-fb80831ab97c)

**Comment by farshadz1997** [comment]
this is a web driver issue, try to delete profiles and run again, or sometime this issue can be solved by restarting. or you can just turn off session
