### ISSUE TITLE
Error in showing points collected

### ISSUE THREAD

**Issue by Curiosity007** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#96]
Rather than subtracting today's point and yesterday's point, I would request you to use this url for checking how much point has been earned - https://rewards.bing.com/status/?form=ANSRW1 

Subtraction does not give correct picture always, especially if we run this more than once in the same day.

**Comment by farshadz1997** [comment]
it doesn't subtract from yesterday's points anymore

**Comment by farshadz1997** [comment]
actually, I can't do this, this request requires saving the first points in a file or accounts file and using them for the second run
